### ISSUE TITLE
[Question] Zephyr support?

### ISSUE THREAD

**Issue by kohnakagawa** [sysprog21/rv32emu-legacy#7]
Can `rv32emu` run Zephyr applications?

In the source code, there are some comments regarding Zephyr RTOS, such as `exit for Zephyr applications` or `for zephyr`. I'm wondering `rv32emu` can run Zephyr applications. If so, could you tell me how to build Zephyr applications for `rv32emu`?

**Comment by kohnakagawa** [comment]
I have solved this issue by myself, so I close this.

**Comment by jserv** [comment]
@kohnakagawa, would you mind if I ask for sending pull request about documentation on Zephyr + rv32emu mini-howto?
